# Generated by Django 5.2.11 on 2026-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_delivery_partner',
            field=models.BooleanField(default=False),
        ),
    ]
