# Generated by Django 5.2.11 on 2026-08-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_id_delivery_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_delivery_partner',
            new_name='is_delivery_partner',
        ),
    ]
