# Generated by Django 5.2.11 on 2026-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0003_category_created_at_deliverypartner_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
