# Generated by Django 5.2.11 on 2026-08-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0008_alter_cartitem_product_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_partenr',
            new_name='delivery_partner',
        ),
    ]
