# Generated by Django 5.2.11 on 2026-08-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0009_rename_delivery_partenr_order_delivery_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Assigned', 'Assigned'), ('Packed', 'Packed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
