# Generated by Django 5.2.11 on 2026-08-12 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0010_alter_order_status_alter_orderstatus_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='phone',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
