# Generated by Django 5.2.11 on 2026-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0012_alter_deliverypartner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
