# Generated by Django 5.2.11 on 2026-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0013_alter_orderstatus_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='user',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryPartner/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
