# Generated by Django 5.2.11 on 2026-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesApp', '0014_remove_deliverypartner_user_deliverypartner_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
